name: email_ingestion_example
description: Example app for email ingestion with infinite scroll
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_ingestion:
    path: ../
  path_provider: ^2.1.1
  signals: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

